# Generated by Django 5.1.4 on 2024-12-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_pics/default_profile_pic.jpg', upload_to='profile_pics/'),
        ),
    ]
